# ==========================================================
# Configuración de la aplicación
# ==========================================================

spring.application.name=confypim-java-spring

# ==========================================================
# Conexión con MySQL
# ==========================================================

spring.datasource.url=jdbc:mysql://localhost:3306/confypim?useSSL=false&serverTimezone=America/Bogota&allowPublicKeyRetrieval=true

spring.datasource.username=root

spring.datasource.password=

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==========================================================
# Configuración de Thymeleaf
# ==========================================================

spring.thymeleaf.cache=false

# ==========================================================
# Configuración del servidor
# ==========================================================

server.port=8080